-- =============================================================================
-- VITPulse — complete database install
--
-- Every file in this folder, concatenated in order, for a single paste into
-- the Supabase SQL editor. Running the numbered files one at a time is easier
-- to debug; this one is for when you know it works.
--
-- Generated by `npm run db:sql`. Do not edit.
-- =============================================================================


-- >>> 01_schema.sql -----------------------------------------------

-- =============================================================================
-- VITPulse — core schema
--
-- Conventions used throughout:
--   * UUID primary keys, defaulted with gen_random_uuid()
--   * created_at / updated_at on every mutable table, maintained by a trigger
--   * enums for closed value sets, so bad data cannot be written at all
--   * foreign keys everywhere, with ON DELETE chosen per relationship
--   * indexes on the columns the repositories actually filter and sort by
-- =============================================================================

create extension if not exists "pgcrypto";
create extension if not exists "pg_trgm";

-- ----------------------------------------------------------------- enums ---
create type user_role as enum (
  'STUDENT','CLUB_MEMBER','CLUB_ADMIN','EDITOR','MODERATOR','ADMIN','SUPER_ADMIN'
);
create type content_status as enum ('DRAFT','PENDING_REVIEW','PUBLISHED','ARCHIVED','REJECTED');
create type post_category as enum (
  'ANNOUNCEMENT','CAMPUS','GUEST','SPORTS','CLUB','EVENT','ACADEMIC','PLACEMENT','OPPORTUNITY','ALERT'
);
create type importance_level as enum ('NORMAL','IMPORTANT','URGENT');
create type event_category as enum (
  'TECHNICAL','CULTURAL','SPORTS','WORKSHOP','HACKATHON','COMPETITION',
  'GUEST_LECTURE','CLUB_RECRUITMENT','PLACEMENT','ACADEMIC'
);
create type club_category as enum (
  'TECHNICAL','CULTURAL','SPORTS','PROFESSIONAL','SOCIAL','REGIONAL','CREATIVE'
);
create type recruitment_status as enum ('OPEN','CLOSED','UPCOMING');
create type club_role as enum ('MEMBER','CORE','LEAD','ADMIN');
create type registration_status as enum ('REGISTERED','WAITLISTED','CANCELLED','ATTENDED');
create type opportunity_type as enum (
  'INTERNSHIP','HACKATHON','COMPETITION','SCHOLARSHIP','RESEARCH',
  'FELLOWSHIP','CAMPUS_JOB','WORKSHOP','CERTIFICATION','PLACEMENT'
);
create type resource_category as enum (
  'ACADEMIC_CALENDAR','TIMETABLE','EXAMINATION','FORMS','IMPORTANT_LINKS','PORTALS',
  'PLACEMENT','SCHOLARSHIP','HOSTEL','LIBRARY','STUDENT_SERVICES','EMERGENCY'
);
create type exam_type as enum ('CAT1','CAT2','FAT','QUIZ','LAB','MAKEUP','RETEST');
create type pyq_source as enum ('UPLOAD','EXTERNAL');
create type ad_placement as enum ('HOME_BANNER','FEED_PROMOTED','SIDEBAR','EVENTS_PROMO','FEATURED_CLUB');
create type ad_status as enum ('DRAFT','PENDING_REVIEW','APPROVED','REJECTED','PAUSED','ENDED');
create type ad_event_kind as enum ('IMPRESSION','CLICK');
create type discussion_category as enum (
  'ACADEMICS','EVENTS','HOSTEL','CAMPUS','CLUBS','PLACEMENTS','GENERAL'
);
create type comment_target as enum ('DISCUSSION','POST','EVENT');
create type vote_target as enum ('DISCUSSION','COMMENT');
create type lost_found_kind as enum ('LOST','FOUND');
create type lost_found_status as enum ('PENDING_REVIEW','OPEN','RESOLVED','REJECTED');
create type contact_method as enum ('EMAIL','PHONE','IN_APP');
create type location_category as enum (
  'ACADEMIC','HOSTEL','LIBRARY','FOOD','SPORTS','AUDITORIUM','ADMIN','MEDICAL','SERVICE','PARKING'
);
-- Where a campus location's coordinate came from. Recorded so the UI can say
-- so, and so an unsourced coordinate can never be added silently.
create type coord_source as enum ('VITAP','OSM');
create type bookmark_target as enum ('POST','EVENT','CLUB','PYQ','OPPORTUNITY','RESOURCE');
create type notification_type as enum (
  'EVENT_REMINDER','CLUB_UPDATE','ANNOUNCEMENT','PYQ_UPLOAD','OPPORTUNITY_DEADLINE','SYSTEM','MODERATION'
);
create type report_target as enum ('POST','COMMENT','DISCUSSION','EVENT','LOST_FOUND','PYQ','AD');
create type report_status as enum ('OPEN','RESOLVED','DISMISSED');

-- --------------------------------------------------- updated_at trigger ---
create or replace function set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ------------------------------------------------------------- profiles ---
-- One row per auth.users row. `id` is the FK so RLS can compare to auth.uid().
create table profiles (
  id                  uuid primary key references auth.users(id) on delete cascade,
  email               text not null unique,
  display_name        text not null,
  username            text not null unique,
  avatar_url          text,
  bio                 text,
  role                user_role not null default 'STUDENT',
  branch              text,
  school              text,
  year                smallint check (year between 1 and 5),
  semester            smallint check (semester between 1 and 10),
  registration_number text,
  interests           text[] not null default '{}',
  suspended           boolean not null default false,
  suspended_reason    text,
  onboarded_at        timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index profiles_role_idx on profiles(role);
create index profiles_branch_year_idx on profiles(branch, year);
create trigger profiles_updated_at before update on profiles
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------- clubs ---
create table clubs (
  id                    uuid primary key default gen_random_uuid(),
  slug                  text not null unique,
  name                  text not null,
  short_name            text not null,
  category              club_category not null,
  tagline               text not null,
  description           text not null,
  logo_url              text,
  banner_url            text,
  school                text,
  email                 text,
  faculty_coordinator   text,
  room                  text,
  recruitment_status    recruitment_status not null default 'CLOSED',
  recruitment_url       text,
  recruitment_closes_at timestamptz,
  membership_info       text,
  verified              boolean not null default false,
  status                content_status not null default 'PENDING_REVIEW',
  follower_count        integer not null default 0 check (follower_count >= 0),
  gallery_urls          text[] not null default '{}',
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
create index clubs_status_category_idx on clubs(status, category);
create index clubs_recruitment_idx on clubs(recruitment_status) where status = 'PUBLISHED';
create index clubs_name_trgm_idx on clubs using gin (name gin_trgm_ops);
create trigger clubs_updated_at before update on clubs
  for each row execute function set_updated_at();

create table club_members (
  id           uuid primary key default gen_random_uuid(),
  club_id      uuid not null references clubs(id) on delete cascade,
  user_id      uuid not null references profiles(id) on delete cascade,
  club_role    club_role not null default 'MEMBER',
  title        text,
  display_name text not null,
  avatar_url   text,
  created_at   timestamptz not null default now(),
  unique (club_id, user_id)
);
create index club_members_user_idx on club_members(user_id);
create index club_members_club_role_idx on club_members(club_id, club_role);

create table club_social_links (
  id       uuid primary key default gen_random_uuid(),
  club_id  uuid not null references clubs(id) on delete cascade,
  platform text not null,
  url      text not null,
  unique (club_id, platform)
);

create table club_follows (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references profiles(id) on delete cascade,
  club_id    uuid not null references clubs(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, club_id)
);
create index club_follows_club_idx on club_follows(club_id);

-- ---------------------------------------------------------------- posts ---
create table posts (
  id              uuid primary key default gen_random_uuid(),
  slug            text not null unique,
  title           text not null,
  summary         text not null,
  body            text not null,
  category        post_category not null,
  importance      importance_level not null default 'NORMAL',
  status          content_status not null default 'DRAFT',
  cover_image_url text,
  cover_image_alt text,
  source          text not null default 'VITPulse Desk',
  location        text,
  event_date      timestamptz,
  tags            text[] not null default '{}',
  author_id       uuid not null references profiles(id) on delete restrict,
  club_id         uuid references clubs(id) on delete set null,
  view_count      integer not null default 0,
  reaction_count  integer not null default 0,
  comment_count   integer not null default 0,
  pinned          boolean not null default false,
  published_at    timestamptz,
  expires_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
-- The feed's hot path: published posts, pinned first, newest first.
create index posts_feed_idx on posts(status, pinned desc, published_at desc);
create index posts_category_idx on posts(category) where status = 'PUBLISHED';
create index posts_club_idx on posts(club_id) where status = 'PUBLISHED';
create index posts_tags_idx on posts using gin (tags);
create index posts_title_trgm_idx on posts using gin (title gin_trgm_ops);
create trigger posts_updated_at before update on posts
  for each row execute function set_updated_at();

-- --------------------------------------------------------------- events ---
create table events (
  id                     uuid primary key default gen_random_uuid(),
  slug                   text not null unique,
  title                  text not null,
  summary                text not null,
  description            text not null,
  category               event_category not null,
  status                 content_status not null default 'DRAFT',
  poster_url             text,
  poster_alt             text,
  club_id                uuid references clubs(id) on delete set null,
  organiser              text not null,
  school                 text,
  venue                  text not null,
  location_id            uuid,
  starts_at              timestamptz not null,
  ends_at                timestamptz not null,
  registration_required  boolean not null default false,
  registration_url       text,
  registration_deadline  timestamptz,
  seats                  integer check (seats is null or seats >= 0),
  seats_taken            integer not null default 0 check (seats_taken >= 0),
  is_paid                boolean not null default false,
  fee_inr                integer not null default 0 check (fee_inr >= 0),
  tags                   text[] not null default '{}',
  contact_email          text,
  created_by             uuid not null references profiles(id) on delete restrict,
  view_count             integer not null default 0,
  featured               boolean not null default false,
  published_at           timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  constraint events_time_order check (ends_at >= starts_at),
  constraint events_fee_matches_paid check ((is_paid and fee_inr > 0) or (not is_paid and fee_inr = 0))
);
create index events_window_idx on events(status, starts_at);
create index events_ends_idx on events(status, ends_at);
create index events_club_idx on events(club_id) where status = 'PUBLISHED';
create index events_category_idx on events(category) where status = 'PUBLISHED';
create index events_tags_idx on events using gin (tags);
create trigger events_updated_at before update on events
  for each row execute function set_updated_at();

create table event_registrations (
  id         uuid primary key default gen_random_uuid(),
  event_id   uuid not null references events(id) on delete cascade,
  user_id    uuid not null references profiles(id) on delete cascade,
  status     registration_status not null default 'REGISTERED',
  note       text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_id, user_id)
);
create index event_registrations_user_idx on event_registrations(user_id);
create trigger event_registrations_updated_at before update on event_registrations
  for each row execute function set_updated_at();

-- -------------------------------------------------------- opportunities ---
create table opportunities (
  id           uuid primary key default gen_random_uuid(),
  slug         text not null unique,
  title        text not null,
  organisation text not null,
  type         opportunity_type not null,
  summary      text not null,
  description  text not null,
  eligibility  text not null,
  location     text not null,
  remote       boolean not null default false,
  stipend      text,
  apply_url    text not null,
  deadline     timestamptz not null,
  status       content_status not null default 'DRAFT',
  tags         text[] not null default '{}',
  branches     text[] not null default '{}',
  years        smallint[] not null default '{}',
  logo_url     text,
  created_by   uuid not null references profiles(id) on delete restrict,
  view_count   integer not null default 0,
  click_count  integer not null default 0,
  published_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index opportunities_deadline_idx on opportunities(status, deadline);
create index opportunities_branches_idx on opportunities using gin (branches);
create trigger opportunities_updated_at before update on opportunities
  for each row execute function set_updated_at();

-- ------------------------------------------------------------ resources ---
create table resources (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique,
  title       text not null,
  description text not null,
  category    resource_category not null,
  url         text not null,
  external    boolean not null default true,
  file_type   text,
  tags        text[] not null default '{}',
  contact     text,
  status      content_status not null default 'PUBLISHED',
  click_count integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index resources_category_idx on resources(status, category);
create trigger resources_updated_at before update on resources
  for each row execute function set_updated_at();

-- ------------------------------------------------------------------ PYQ ---
create table pyq_subjects (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique,
  name        text not null,
  branch      text not null,
  semester    smallint not null check (semester between 1 and 10),
  credits     smallint,
  faculty     text,
  paper_count integer not null default 0 check (paper_count >= 0)
);
create index pyq_subjects_branch_sem_idx on pyq_subjects(branch, semester);

create table pyq_papers (
  id              uuid primary key default gen_random_uuid(),
  subject_id      uuid not null references pyq_subjects(id) on delete cascade,
  subject_code    text not null,
  subject_name    text not null,
  branch          text not null,
  semester        smallint not null,
  year            smallint not null,
  exam_type       exam_type not null,
  slot            text,
  file_url        text not null,
  file_size_bytes integer,
  page_count      smallint,
  source_kind     pyq_source not null default 'UPLOAD',
  external_id     text,
  status          content_status not null default 'PENDING_REVIEW',
  uploaded_by     uuid references profiles(id) on delete set null,
  download_count  integer not null default 0,
  report_count    integer not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index pyq_papers_lookup_idx on pyq_papers(status, branch, semester);
create index pyq_papers_subject_idx on pyq_papers(subject_id, year desc);
create index pyq_papers_popular_idx on pyq_papers(status, download_count desc);
create trigger pyq_papers_updated_at before update on pyq_papers
  for each row execute function set_updated_at();

create table pyq_requests (
  id            uuid primary key default gen_random_uuid(),
  subject_code  text not null,
  subject_name  text not null,
  branch        text not null,
  semester      smallint not null,
  detail        text not null,
  requested_by  uuid not null references profiles(id) on delete cascade,
  status        text not null default 'OPEN',
  created_at    timestamptz not null default now()
);

-- ------------------------------------------------------------------ ads ---
create table ads (
  id              uuid primary key default gen_random_uuid(),
  club_id         uuid not null references clubs(id) on delete cascade,
  name            text not null,
  headline        text not null,
  body            text not null,
  cta_label       text not null,
  cta_url         text not null,
  image_url       text,
  image_alt       text,
  placement       ad_placement not null,
  status          ad_status not null default 'PENDING_REVIEW',
  starts_at       timestamptz not null,
  ends_at         timestamptz not null,
  priority        smallint not null default 10 check (priority between 0 and 100),
  impression_cap  integer check (impression_cap is null or impression_cap > 0),
  impression_count integer not null default 0,
  click_count     integer not null default 0,
  reviewed_by     uuid references profiles(id) on delete set null,
  review_note     text,
  created_by      uuid not null references profiles(id) on delete restrict,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint ads_window check (ends_at > starts_at)
);
-- Ad selection filters on placement + status and orders by priority.
create index ads_serving_idx on ads(placement, status, priority desc);
create index ads_club_idx on ads(club_id);
create trigger ads_updated_at before update on ads
  for each row execute function set_updated_at();

create table ad_events (
  id         uuid primary key default gen_random_uuid(),
  ad_id      uuid not null references ads(id) on delete cascade,
  kind       ad_event_kind not null,
  -- Deduplicates repeat counts per visitor per bucket without storing identity.
  dedupe_key text not null,
  created_at timestamptz not null default now(),
  unique (kind, dedupe_key)
);
create index ad_events_ad_idx on ad_events(ad_id, created_at desc);

-- ------------------------------------------------------------ community ---
create table discussions (
  id            uuid primary key default gen_random_uuid(),
  slug          text not null unique,
  title         text not null,
  body          text not null,
  category      discussion_category not null,
  author_id     uuid not null references profiles(id) on delete cascade,
  upvote_count  integer not null default 0,
  comment_count integer not null default 0,
  locked        boolean not null default false,
  hidden        boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index discussions_list_idx on discussions(hidden, created_at desc);
create index discussions_category_idx on discussions(category) where hidden = false;
create trigger discussions_updated_at before update on discussions
  for each row execute function set_updated_at();

create table comments (
  id           uuid primary key default gen_random_uuid(),
  target_type  comment_target not null,
  target_id    uuid not null,
  parent_id    uuid references comments(id) on delete cascade,
  author_id    uuid not null references profiles(id) on delete cascade,
  body         text not null,
  upvote_count integer not null default 0,
  hidden       boolean not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index comments_target_idx on comments(target_type, target_id, created_at);
create trigger comments_updated_at before update on comments
  for each row execute function set_updated_at();

create table votes (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references profiles(id) on delete cascade,
  target_type vote_target not null,
  target_id   uuid not null,
  created_at  timestamptz not null default now(),
  -- One vote per user per item: makes the toggle idempotent.
  unique (user_id, target_type, target_id)
);

create table lost_found (
  id             uuid primary key default gen_random_uuid(),
  kind           lost_found_kind not null,
  title          text not null,
  description    text not null,
  image_url      text,
  location_text  text not null,
  happened_on    timestamptz not null,
  contact_method contact_method not null default 'IN_APP',
  contact_value  text not null,
  status         lost_found_status not null default 'PENDING_REVIEW',
  reporter_id    uuid not null references profiles(id) on delete cascade,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index lost_found_status_idx on lost_found(status, happened_on desc);
create trigger lost_found_updated_at before update on lost_found
  for each row execute function set_updated_at();

-- ------------------------------------------------------- campus & admin ---
create table campus_locations (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique,
  name        text not null,
  short_name  text not null,
  category    location_category not null,
  description text not null,
  timings     text,
  contact     text,
  -- Nullable throughout: a place with no published coordinate is recorded as
  -- unplaced rather than given a plausible-looking guess.
  map_x        numeric(5,2),
  map_y        numeric(5,2),
  lat          numeric(9,6),
  lng          numeric(9,6),
  levels       smallint,
  coord_source coord_source,
  tags         text[] not null default '{}'
);

alter table events
  add constraint events_location_fk
  foreign key (location_id) references campus_locations(id) on delete set null;

create table bookmarks (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references profiles(id) on delete cascade,
  target_type bookmark_target not null,
  target_id   text not null,
  created_at  timestamptz not null default now(),
  unique (user_id, target_type, target_id)
);
create index bookmarks_user_type_idx on bookmarks(user_id, target_type, created_at desc);

create table notifications (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references profiles(id) on delete cascade,
  type       notification_type not null,
  title      text not null,
  body       text not null,
  href       text,
  read_at    timestamptz,
  created_at timestamptz not null default now()
);
create index notifications_inbox_idx on notifications(user_id, created_at desc);
create index notifications_unread_idx on notifications(user_id) where read_at is null;

create table notification_prefs (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references profiles(id) on delete cascade,
  type       notification_type not null,
  enabled    boolean not null default true,
  updated_at timestamptz not null default now(),
  unique (user_id, type)
);

create table reports (
  id              uuid primary key default gen_random_uuid(),
  target_type     report_target not null,
  target_id       text not null,
  reason          text not null,
  detail          text,
  reporter_id     uuid not null references profiles(id) on delete cascade,
  status          report_status not null default 'OPEN',
  resolved_by     uuid references profiles(id) on delete set null,
  resolution_note text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index reports_queue_idx on reports(status, created_at desc);
create trigger reports_updated_at before update on reports
  for each row execute function set_updated_at();

create table audit_logs (
  id          uuid primary key default gen_random_uuid(),
  actor_id    uuid references profiles(id) on delete set null,
  actor_name  text not null,
  action      text not null,
  entity_type text not null,
  entity_id   text not null,
  detail      text,
  created_at  timestamptz not null default now()
);
create index audit_logs_recent_idx on audit_logs(created_at desc);
create index audit_logs_entity_idx on audit_logs(entity_type, entity_id);

create table analytics_events (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  path         text not null,
  entity_id    text,
  -- A daily-rotating hash. Not reversible, and meaningless after 24 hours.
  visitor_hash text not null,
  meta         jsonb not null default '{}',
  created_at   timestamptz not null default now()
);
create index analytics_events_range_idx on analytics_events(created_at desc);
create index analytics_events_name_idx on analytics_events(name, created_at desc);


-- >>> 02_functions.sql --------------------------------------------

-- =============================================================================
-- Helper functions
--
-- These are SECURITY DEFINER, so they run with the definer's rights. Each one
-- therefore validates its own inputs against a hard allowlist — a SECURITY
-- DEFINER function that interpolates caller-supplied identifiers would be an
-- injection hole regardless of RLS.
-- =============================================================================

-- The caller's role, read from their profile. Used by every policy below.
-- STABLE so Postgres can cache it per statement rather than per row.
create or replace function auth_role() returns user_role
language sql stable security definer set search_path = public as $$
  select coalesce(
    (select case when p.suspended then 'STUDENT'::user_role else p.role end
       from profiles p where p.id = auth.uid()),
    'STUDENT'::user_role
  );
$$;

-- Membership rank check: does the caller hold at least this platform role?
create or replace function has_role(minimum user_role) returns boolean
language sql stable security definer set search_path = public as $$
  select case minimum
    when 'STUDENT'     then true
    when 'CLUB_MEMBER' then auth_role() <> 'STUDENT'
    when 'CLUB_ADMIN'  then auth_role() in ('CLUB_ADMIN','EDITOR','MODERATOR','ADMIN','SUPER_ADMIN')
    when 'EDITOR'      then auth_role() in ('EDITOR','ADMIN','SUPER_ADMIN')
    when 'MODERATOR'   then auth_role() in ('MODERATOR','ADMIN','SUPER_ADMIN')
    when 'ADMIN'       then auth_role() in ('ADMIN','SUPER_ADMIN')
    when 'SUPER_ADMIN' then auth_role() = 'SUPER_ADMIN'
    else false
  end;
$$;

-- Does the caller administer this club?
create or replace function administers_club(target uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from club_members m
    where m.club_id = target and m.user_id = auth.uid() and m.club_role = 'ADMIN'
  );
$$;

-- Is the caller a member of this club in any capacity?
create or replace function in_club(target uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from club_members m where m.club_id = target and m.user_id = auth.uid()
  );
$$;

-- ---------------------------------------------------------------------------
-- Counter increment.
--
-- View, download and impression counters must not be a read-modify-write from
-- the application: concurrent requests would lose updates. This does it in one
-- statement. The (table, column) pair is checked against a fixed allowlist, so
-- the dynamic SQL can only ever target a known counter.
-- ---------------------------------------------------------------------------
create or replace function bump_counter(p_table text, p_column text, p_id uuid, p_by integer default 1)
returns void
language plpgsql security definer set search_path = public as $$
declare
  allowed constant text[] := array[
    'posts.view_count','posts.reaction_count','posts.comment_count',
    'events.view_count','events.seats_taken',
    'clubs.follower_count',
    'opportunities.view_count','opportunities.click_count',
    'resources.click_count',
    'pyq_papers.download_count','pyq_papers.report_count',
    'pyq_subjects.paper_count',
    'ads.impression_count','ads.click_count',
    'discussions.upvote_count','discussions.comment_count',
    'comments.upvote_count'
  ];
  target text := p_table || '.' || p_column;
begin
  if not (target = any (allowed)) then
    raise exception 'bump_counter: % is not an allowed counter', target;
  end if;

  -- Identifiers are quoted; the allowlist above already constrains them to a
  -- known set, so this cannot be steered by caller input.
  execute format(
    'update %I set %I = greatest(0, coalesce(%I, 0) + $1) where id = $2',
    p_table, p_column, p_column
  ) using p_by, p_id;
end;
$$;

revoke all on function bump_counter(text, text, uuid, integer) from public;
grant execute on function bump_counter(text, text, uuid, integer) to authenticated, anon;

-- ---------------------------------------------------------------------------
-- Profile provisioning.
--
-- Creates the profile row when a new auth user appears, so the application
-- never has to race the trigger. The first account matching a bootstrap email
-- is promoted to SUPER_ADMIN.
-- ---------------------------------------------------------------------------
create or replace function handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  base_username text;
  final_username text;
  suffix integer := 0;
  bootstrap text[] := string_to_array(
    coalesce(current_setting('app.super_admin_emails', true), ''), ','
  );
begin
  base_username := regexp_replace(split_part(new.email, '@', 1), '[^a-zA-Z0-9]', '', 'g');
  base_username := lower(left(nullif(base_username, ''), 24));
  if base_username is null then base_username := 'student'; end if;

  final_username := base_username;
  while exists (select 1 from profiles where username = final_username) loop
    suffix := suffix + 1;
    final_username := base_username || suffix::text;
  end loop;

  insert into profiles (id, email, display_name, username, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', base_username),
    final_username,
    case when lower(new.email) = any (bootstrap) then 'SUPER_ADMIN'::user_role else 'STUDENT'::user_role end
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ---------------------------------------------------------------------------
-- Keep denormalised counters honest even if the application forgets.
-- ---------------------------------------------------------------------------
create or replace function sync_club_follower_count() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if TG_OP = 'INSERT' then
    update clubs set follower_count = follower_count + 1 where id = new.club_id;
  elsif TG_OP = 'DELETE' then
    update clubs set follower_count = greatest(0, follower_count - 1) where id = old.club_id;
  end if;
  return null;
end;
$$;

create trigger club_follows_count
  after insert or delete on club_follows
  for each row execute function sync_club_follower_count();


-- >>> 03_rls.sql --------------------------------------------------

-- =============================================================================
-- Row Level Security
--
-- RLS is enabled on every table. The rules below are the *last* line of defence:
-- the application already checks permissions in `requirePermission`, but a bug
-- there must not become a data breach.
--
-- Reading model: published content is public; personal rows are visible only to
-- their owner; moderation and audit surfaces require a staff role.
-- Writing model: students write only rows they own; everything else needs a
-- role, and club-scoped writes additionally need club administration.
-- =============================================================================

alter table profiles            enable row level security;
alter table clubs               enable row level security;
alter table club_members        enable row level security;
alter table club_social_links   enable row level security;
alter table club_follows        enable row level security;
alter table posts               enable row level security;
alter table events              enable row level security;
alter table event_registrations enable row level security;
alter table opportunities       enable row level security;
alter table resources           enable row level security;
alter table pyq_subjects        enable row level security;
alter table pyq_papers          enable row level security;
alter table pyq_requests        enable row level security;
alter table ads                 enable row level security;
alter table ad_events           enable row level security;
alter table discussions         enable row level security;
alter table comments            enable row level security;
alter table votes               enable row level security;
alter table lost_found          enable row level security;
alter table campus_locations    enable row level security;
alter table bookmarks           enable row level security;
alter table notifications       enable row level security;
alter table notification_prefs  enable row level security;
alter table reports             enable row level security;
alter table audit_logs          enable row level security;
alter table analytics_events    enable row level security;

-- ------------------------------------------------------------- profiles ---
-- Every signed-in student can see the public shape of other profiles (names
-- appear next to posts); only the owner or an admin can change one.
create policy profiles_select on profiles for select
  using (true);

create policy profiles_update_own on profiles for update
  using (id = auth.uid()) with check (id = auth.uid());

create policy profiles_update_staff on profiles for update
  using (has_role('ADMIN')) with check (has_role('ADMIN'));

create policy profiles_insert_self on profiles for insert
  with check (id = auth.uid());

-- ---------------------------------------------------------------- clubs ---
create policy clubs_select on clubs for select
  using (status = 'PUBLISHED' or has_role('MODERATOR') or administers_club(id));

create policy clubs_insert on clubs for insert
  with check (has_role('ADMIN'));

create policy clubs_update on clubs for update
  using (administers_club(id) or has_role('ADMIN'))
  with check (administers_club(id) or has_role('ADMIN'));

create policy clubs_delete on clubs for delete using (has_role('ADMIN'));

create policy club_members_select on club_members for select using (true);
create policy club_members_write on club_members for all
  using (administers_club(club_id) or has_role('ADMIN'))
  with check (administers_club(club_id) or has_role('ADMIN'));

create policy club_socials_select on club_social_links for select using (true);
create policy club_socials_write on club_social_links for all
  using (administers_club(club_id) or has_role('ADMIN'))
  with check (administers_club(club_id) or has_role('ADMIN'));

-- A follow row belongs to the follower; the club sees only its aggregate count.
create policy club_follows_select on club_follows for select
  using (user_id = auth.uid() or administers_club(club_id) or has_role('ADMIN'));
create policy club_follows_insert on club_follows for insert
  with check (user_id = auth.uid());
create policy club_follows_delete on club_follows for delete
  using (user_id = auth.uid());

-- ---------------------------------------------------------------- posts ---
create policy posts_select on posts for select
  using (
    status = 'PUBLISHED'
    or author_id = auth.uid()
    or has_role('EDITOR')
    or (club_id is not null and administers_club(club_id))
  );

create policy posts_insert on posts for insert
  with check (
    author_id = auth.uid()
    and (
      has_role('EDITOR')
      or (club_id is not null and administers_club(club_id))
    )
    -- Only an editor may create something already published.
    and (status <> 'PUBLISHED' or has_role('EDITOR'))
  );

create policy posts_update on posts for update
  using (
    has_role('EDITOR')
    or author_id = auth.uid()
    or (club_id is not null and administers_club(club_id))
  )
  with check (status <> 'PUBLISHED' or has_role('EDITOR'));

create policy posts_delete on posts for delete using (has_role('ADMIN'));

-- --------------------------------------------------------------- events ---
create policy events_select on events for select
  using (
    status = 'PUBLISHED'
    or created_by = auth.uid()
    or has_role('EDITOR')
    or (club_id is not null and administers_club(club_id))
  );

create policy events_insert on events for insert
  with check (
    created_by = auth.uid()
    and (has_role('EDITOR') or (club_id is not null and administers_club(club_id)))
    and (status <> 'PUBLISHED' or has_role('EDITOR'))
  );

create policy events_update on events for update
  using (
    has_role('EDITOR')
    or created_by = auth.uid()
    or (club_id is not null and administers_club(club_id))
  )
  with check (status <> 'PUBLISHED' or has_role('EDITOR'));

create policy events_delete on events for delete using (has_role('ADMIN'));

-- A student sees only their own registrations; club admins see their event's.
create policy registrations_select on event_registrations for select
  using (
    user_id = auth.uid()
    or has_role('EDITOR')
    or exists (
      select 1 from events e
      where e.id = event_id and e.club_id is not null and administers_club(e.club_id)
    )
  );
create policy registrations_insert on event_registrations for insert
  with check (user_id = auth.uid());
create policy registrations_update on event_registrations for update
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ------------------------------------------------- opportunities & docs ---
create policy opportunities_select on opportunities for select
  using (status = 'PUBLISHED' or has_role('EDITOR'));
create policy opportunities_write on opportunities for all
  using (has_role('EDITOR')) with check (has_role('EDITOR'));

create policy resources_select on resources for select
  using (status = 'PUBLISHED' or has_role('EDITOR'));
create policy resources_write on resources for all
  using (has_role('EDITOR')) with check (has_role('EDITOR'));

create policy locations_select on campus_locations for select using (true);
create policy locations_write on campus_locations for all
  using (has_role('ADMIN')) with check (has_role('ADMIN'));

-- ------------------------------------------------------------------ PYQ ---
create policy pyq_subjects_select on pyq_subjects for select using (true);
create policy pyq_subjects_write on pyq_subjects for all
  using (has_role('EDITOR')) with check (has_role('EDITOR'));

-- An uploader can see their own paper while it waits for review.
create policy pyq_papers_select on pyq_papers for select
  using (status = 'PUBLISHED' or uploaded_by = auth.uid() or has_role('EDITOR'));

create policy pyq_papers_insert on pyq_papers for insert
  with check (
    uploaded_by = auth.uid()
    -- A student can never self-publish; approval is an editor action.
    and status = 'PENDING_REVIEW'
  );

create policy pyq_papers_update on pyq_papers for update
  using (has_role('EDITOR')) with check (has_role('EDITOR'));

create policy pyq_papers_delete on pyq_papers for delete using (has_role('ADMIN'));

create policy pyq_requests_select on pyq_requests for select
  using (requested_by = auth.uid() or has_role('EDITOR'));
create policy pyq_requests_insert on pyq_requests for insert
  with check (requested_by = auth.uid());

-- ------------------------------------------------------------------ ads ---
-- Only approved campaigns are readable by students; a club sees its own.
create policy ads_select on ads for select
  using (status = 'APPROVED' or administers_club(club_id) or has_role('MODERATOR'));

create policy ads_insert on ads for insert
  with check (
    created_by = auth.uid()
    and administers_club(club_id)
    -- A club can submit, never approve.
    and status in ('DRAFT','PENDING_REVIEW')
  );

create policy ads_update_own on ads for update
  using (administers_club(club_id))
  with check (administers_club(club_id) and status in ('DRAFT','PENDING_REVIEW','PAUSED'));

create policy ads_update_staff on ads for update
  using (has_role('MODERATOR')) with check (has_role('MODERATOR'));

-- Ad events are written by the service role only; clubs read their own totals.
create policy ad_events_select on ad_events for select
  using (
    has_role('MODERATOR')
    or exists (select 1 from ads a where a.id = ad_id and administers_club(a.club_id))
  );

-- ------------------------------------------------------------ community ---
create policy discussions_select on discussions for select
  using (hidden = false or author_id = auth.uid() or has_role('MODERATOR'));
create policy discussions_insert on discussions for insert
  with check (author_id = auth.uid());
create policy discussions_update on discussions for update
  using (author_id = auth.uid() or has_role('MODERATOR'))
  with check (author_id = auth.uid() or has_role('MODERATOR'));
create policy discussions_delete on discussions for delete using (has_role('MODERATOR'));

create policy comments_select on comments for select
  using (hidden = false or author_id = auth.uid() or has_role('MODERATOR'));
create policy comments_insert on comments for insert
  with check (author_id = auth.uid());
create policy comments_update on comments for update
  using (author_id = auth.uid() or has_role('MODERATOR'))
  with check (author_id = auth.uid() or has_role('MODERATOR'));
create policy comments_delete on comments for delete using (has_role('MODERATOR'));

create policy votes_select on votes for select using (user_id = auth.uid());
create policy votes_insert on votes for insert with check (user_id = auth.uid());
create policy votes_delete on votes for delete using (user_id = auth.uid());

-- Open listings are public, but the contact column is only exposed through the
-- application's own projection — see `toPublicLostFound`.
create policy lost_found_select on lost_found for select
  using (status = 'OPEN' or reporter_id = auth.uid() or has_role('MODERATOR'));
create policy lost_found_insert on lost_found for insert
  with check (reporter_id = auth.uid() and status = 'PENDING_REVIEW');
create policy lost_found_update on lost_found for update
  using (reporter_id = auth.uid() or has_role('MODERATOR'))
  with check (reporter_id = auth.uid() or has_role('MODERATOR'));

-- ------------------------------------------------------------- personal ---
-- The rule that matters for "users cannot modify another user's bookmarks".
create policy bookmarks_all on bookmarks for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy notifications_select on notifications for select using (user_id = auth.uid());
create policy notifications_update on notifications for update
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy notification_prefs_all on notification_prefs for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ------------------------------------------------- moderation and audit ---
create policy reports_select on reports for select
  using (reporter_id = auth.uid() or has_role('MODERATOR'));
create policy reports_insert on reports for insert
  with check (reporter_id = auth.uid());
create policy reports_update on reports for update
  using (has_role('MODERATOR')) with check (has_role('MODERATOR'));

-- The audit log is append-only from the application's perspective: no update or
-- delete policy exists, so those operations are denied for every non-service role.
create policy audit_logs_select on audit_logs for select using (has_role('ADMIN'));

-- Analytics rows are written by the service role and read by staff only.
create policy analytics_select on analytics_events for select using (has_role('EDITOR'));


-- >>> 04_storage.sql ----------------------------------------------

-- =============================================================================
-- Storage buckets
--
-- `pyq-papers` is private: papers are served through short-lived signed URLs so
-- the library cannot be scraped from a guessable public path.
-- `media` is public, because logos and posters are embedded in pages and cached
-- by the CDN.
-- =============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('pyq-papers', 'pyq-papers', false, 15728640, array['application/pdf']),
  ('media',      'media',      true,   5242880, array['image/jpeg','image/png','image/webp','image/avif'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Any signed-in student may upload a paper; only staff may overwrite or delete.
create policy "pyq upload" on storage.objects for insert to authenticated
  with check (bucket_id = 'pyq-papers');

create policy "pyq read staff" on storage.objects for select to authenticated
  using (bucket_id = 'pyq-papers' and has_role('EDITOR'));

create policy "pyq manage" on storage.objects for update to authenticated
  using (bucket_id = 'pyq-papers' and has_role('EDITOR'));

create policy "pyq delete" on storage.objects for delete to authenticated
  using (bucket_id = 'pyq-papers' and has_role('ADMIN'));

-- Media is world-readable; writes need at least a club admin.
create policy "media read" on storage.objects for select
  using (bucket_id = 'media');

create policy "media write" on storage.objects for insert to authenticated
  with check (bucket_id = 'media' and has_role('CLUB_ADMIN'));

create policy "media manage" on storage.objects for update to authenticated
  using (bucket_id = 'media' and has_role('CLUB_ADMIN'));

create policy "media delete" on storage.objects for delete to authenticated
  using (bucket_id = 'media' and has_role('ADMIN'));


-- >>> 05_reference_data.sql ---------------------------------------

-- =============================================================================
-- Reference data — real VIT-AP institutional records
--
-- Generated from src/data/vitap.ts. Do not edit by hand: run `npm run db:sql`.
--
-- Everything here is fact taken from VIT-AP's own public pages and from
-- OpenStreetMap (ODbL) — campus locations with real coordinates, the registered
-- clubs and chapters, and the official portal links. It is NOT demo content.
-- Last verified: 2026-08-31.
--
-- Safe to re-run: every statement upserts on the natural key.
-- =============================================================================

insert into campus_locations
  (slug, name, short_name, category, description, timings, contact,
   map_x, map_y, lat, lng, levels, coord_source, tags)
values
  ('main-entrance', 'Main Entrance', 'Gate', 'SERVICE', 'The main gate on the northern edge of campus, off the road that connects to NH-16. Security check, visitor registration and the drop-off point for cabs and buses.', '24 hours', null, 52.5, 6.9, 16.4970554, 80.4991965, null, 'VITAP', array['gate', 'entrance', 'security', 'visitors']),
  ('visitor-parking', 'Visitor Parking', 'Parking', 'PARKING', 'Surface parking just inside the main gate, on the eastern side of the approach road. Used by visitors and parents on campus for the day.', '24 hours', null, 58.6, 12.4, 16.4967217, 80.4995822, null, 'OSM', array['parking', 'visitors', 'vehicles']),
  ('transport-bay', 'Transport Bay', 'Transport', 'PARKING', 'The bus and transport bay beside the approach road, where university buses to Vijayawada, Guntur and Mangalagiri pick up and set down.', '05:30 - 22:30', null, 45.4, 12.3, 16.4967287, 80.498748, null, 'OSM', array['bus', 'transport', 'shuttle', 'commute']),
  ('mgr-block', 'M.G.R Block', 'MGR', 'ADMIN', 'The main administrative building, named after Dr. M.G. Ramachandran. Houses the offices of the Chancellor, Vice Chancellor and Registrar along with the managerial offices.', '09:00 - 17:30', null, null, null, null, null, null, null, array['administration', 'registrar', 'chancellor', 'offices']),
  ('ab1-sarvepalli-radhakrishnan-block', 'Sarvepalli Radhakrishnan Academic Block (AB-1)', 'AB-1', 'ACADEMIC', 'A three-storey academic block on the eastern side of the central lawn, with lecture halls, laboratories and faculty cabins.', '08:00 - 18:00', null, 71.7, 28.1, 16.495775, 80.5004053, 3, 'OSM', array['academic', 'classrooms', 'labs', 'ab1']),
  ('ab2-apj-abdul-kalam-block', 'APJ Abdul Kalam Academic Block (AB-2)', 'AB-2', 'ACADEMIC', 'A three-storey academic block on the western side of the central lawn, mirroring AB-1, with lecture halls, laboratories and workshops.', '08:00 - 18:00', null, 35.5, 28.7, 16.4957371, 80.498128, 3, 'OSM', array['academic', 'classrooms', 'labs', 'ab2']),
  ('central-block', 'Mahatma Gandhi Academic Block (Central Block)', 'CB', 'ACADEMIC', 'The eleven-storey block at the heart of campus, the tallest building on site. Lecture theatres, seminar halls and school offices across its floors.', '08:00 - 18:00', null, 52.4, 51.7, 16.4943535, 80.4991899, 11, 'OSM', array['academic', 'central block', 'cb', 'lecture theatres']),
  ('central-junction', 'Central Junction & Fountain', 'Junction', 'SERVICE', 'The fountain and open plaza where the campus paths converge, between the Central Block and the academic blocks. The default meeting point on campus.', '24 hours', null, 52.5, 46, 16.4946963, 80.4991941, null, 'OSM', array['fountain', 'meeting point', 'plaza', 'junction']),
  ('auditorium', 'Auditorium', 'Audi', 'AUDITORIUM', 'The main auditorium beside AB-2, used for convocations, guest lectures, cultural nights and university-wide events.', 'Event dependent', null, 38.7, 25.1, 16.4959587, 80.4983284, null, 'OSM', array['auditorium', 'events', 'cultural', 'lectures']),
  ('library', 'Central Library', 'Library', 'LIBRARY', 'The central library with print and digital collections, subscribed journal databases, reading halls and discussion rooms.', '08:00 - 24:00 (extended during exams)', null, null, null, null, null, null, null, array['library', 'study', 'journals', 'reading']),
  ('rock-plaza', 'Rock Plaza', 'Rock Plaza', 'FOOD', 'The food court on the western side of campus, near AB-2 and the gym. Multiple counters and the main daytime eating spot between classes.', '07:30 - 22:00', null, 32.2, 41.6, 16.4949631, 80.4979211, null, 'OSM', array['food court', 'cafeteria', 'lunch', 'canteen']),
  ('food-street', 'Food Street', 'Food St', 'FOOD', 'The row of outlets in the southern half of campus, between the Central Block and the hostels.', '08:00 - 23:00', null, 39, 63, 16.4936691, 80.4983456, null, 'OSM', array['food', 'outlets', 'snacks', 'dinner']),
  ('mh2-food-store', 'MH-2 Food Store', 'MH-2 Store', 'FOOD', 'The store and quick-service counter beside MH-2, the late-night option for residents of the men''s hostel blocks.', 'Late night', null, 80.5, 61.3, 16.4937706, 80.5009574, null, 'OSM', array['night canteen', 'store', 'hostel', 'snacks']),
  ('health-centre', 'Health Centre', 'Health', 'MEDICAL', 'The campus health centre with resident medical officers and nursing staff, running round the clock for residents. Ambulance dispatch for emergencies.', '24 hours', null, null, null, null, null, null, null, array['medical', 'doctor', 'emergency', 'ambulance']),
  ('paid-gym', 'Gym', 'Gym', 'SPORTS', 'The fitness centre on the western side of campus, near Rock Plaza.', '05:30 - 21:30', null, 30.2, 44.4, 16.4947946, 80.4977939, null, 'OSM', array['gym', 'fitness', 'workout']),
  ('sports-triangle', 'Sports Triangle', 'Triangle', 'SPORTS', 'The open sports ground in the south-west of campus, used for football, athletics and evening practice.', '05:30 - 21:00', null, 17, 63.6, 16.493631, 80.4969615, null, 'OSM', array['ground', 'football', 'athletics', 'practice']),
  ('cricket-ground', 'Cricket Ground', 'Cricket', 'SPORTS', 'The cricket ground on the eastern side of campus, beside the men''s hostel blocks.', '05:30 - 21:00', null, 79, 41.1, 16.4949911, 80.5008666, null, 'OSM', array['cricket', 'ground', 'nets']),
  ('basketball-court', 'New Basketball Court', 'Basketball', 'SPORTS', 'The basketball court near the men''s hostel blocks, floodlit for evening play.', '05:30 - 22:00', null, 75.8, 62.3, 16.4937117, 80.5006649, null, 'OSM', array['basketball', 'court', 'evening']),
  ('mh-1', 'Men''s Hostel MH-1 (Sarojini Naidu Block)', 'MH-1', 'HOSTEL', 'A men''s residential block with AC and non-AC rooms, a resident warden on duty and a provision store in the block.', '24 hours', 'Men''s hostel office · 0863-2370501', 75.6, 54.7, 16.4941688, 80.5006523, null, 'OSM', array['hostel', 'mh1', 'residence']),
  ('mh-2', 'Men''s Hostel MH-2 (Rabindranath Tagore Block)', 'MH-2', 'HOSTEL', 'A men''s residential block with AC and non-AC rooms and a food store beside it.', '24 hours', 'Men''s hostel office · 0863-2370501', 86.3, 65.5, 16.493519, 80.5013236, null, 'OSM', array['hostel', 'mh2', 'residence']),
  ('mh-3', 'Men''s Hostel MH-3 (Neelam Sanjiva Reddy Block)', 'MH-3', 'HOSTEL', 'A men''s residential block in the south-east corner of the hostel zone.', '24 hours', 'Men''s hostel office · 0863-2370501', 87.2, 88.3, 16.4921453, 80.5013775, null, 'OSM', array['hostel', 'mh3', 'residence']),
  ('mh-4', 'Men''s Hostel MH-4', 'MH-4', 'HOSTEL', 'A fourteen-storey men''s residential block in the southern hostel zone.', '24 hours', 'Men''s hostel office · 0863-2370501', 78.4, 91.3, 16.4919627, 80.5008241, 14, 'OSM', array['hostel', 'mh4', 'residence']),
  ('mh-5', 'Men''s Hostel MH-5', 'MH-5', 'HOSTEL', 'A fourteen-storey men''s residential block at the northern end of the hostel zone.', '24 hours', 'Men''s hostel office · 0863-2370501', 85.3, 55.6, 16.4941142, 80.5012582, 14, 'OSM', array['hostel', 'mh5', 'residence']),
  ('mh-6', 'Men''s Hostel MH-6', 'MH-6', 'HOSTEL', 'A men''s residential block on the western edge of the hostel zone.', '24 hours', 'Men''s hostel office · 0863-2370501', 61.7, 90.6, 16.4920053, 80.4997767, null, 'OSM', array['hostel', 'mh6', 'residence']),
  ('mh-7', 'Men''s Hostel MH-7', 'MH-7', 'HOSTEL', 'A men''s residential block in the middle of the hostel zone.', '24 hours', 'Men''s hostel office · 0863-2370501', 72.7, 79.2, 16.4926946, 80.5004664, null, 'OSM', array['hostel', 'mh7', 'residence']),
  ('lh-1', 'Ladies'' Hostel LH-1', 'LH-1', 'HOSTEL', 'A women''s residential block in the south-west of campus, with a resident warden on duty and a provision store in the block.', '24 hours', 'Ladies'' hostel office · 0863-2370600', 12.8, 90.5, 16.4920124, 80.4966996, null, 'OSM', array['hostel', 'lh1', 'residence']),
  ('lh-2', 'Ladies'' Hostel LH-2', 'LH-2', 'HOSTEL', 'A fourteen-storey women''s residential block in the south-west of campus.', '24 hours', 'Ladies'' hostel office · 0863-2370600', 23.4, 93.1, 16.4918534, 80.4973656, 14, 'OSM', array['hostel', 'lh2', 'residence']),
  ('lh-3', 'Ladies'' Hostel LH-3', 'LH-3', 'HOSTEL', 'A fourteen-storey women''s residential block, the closest of the women''s blocks to the academic core.', '24 hours', 'Ladies'' hostel office · 0863-2370600', 26.5, 78.8, 16.4927191, 80.4975609, 14, 'OSM', array['hostel', 'lh3', 'residence']),
  ('incubation-centre', 'Innovation & Incubation Centre', 'Incubation', 'ACADEMIC', 'The centre supporting student startups and prototypes, with maker space, mentoring and the university''s incubation programme.', '09:00 - 18:00', null, null, null, null, null, null, null, array['startup', 'incubation', 'innovation', 'prototype']),
  ('research-centres', 'Centres of Excellence', 'CoE', 'ACADEMIC', 'The research centres and centres of excellence, running funded projects across the schools.', '09:00 - 18:00', null, null, null, null, null, null, null, array['research', 'coe', 'projects', 'labs']),
  ('guest-house', 'Guest House & Parent Stay', 'Guest House', 'SERVICE', 'On-campus accommodation for visiting parents, guests and invited speakers. Booked through the front office.', '24 hours', null, null, null, null, null, null, null, array['guest house', 'parents', 'stay', 'visitors']),
  ('bank-and-atm', 'Bank & ATM', 'Bank', 'SERVICE', 'The on-campus bank branch and ATM for fee payment, account services and cash withdrawal.', '10:00 - 16:00 (ATM 24 hours)', null, null, null, null, null, null, null, array['bank', 'atm', 'cash', 'fees'])
on conflict (slug) do update set
  name         = excluded.name,
  short_name   = excluded.short_name,
  category     = excluded.category,
  description  = excluded.description,
  timings      = excluded.timings,
  contact      = excluded.contact,
  map_x        = excluded.map_x,
  map_y        = excluded.map_y,
  lat          = excluded.lat,
  lng          = excluded.lng,
  levels       = excluded.levels,
  coord_source = excluded.coord_source,
  tags         = excluded.tags;


insert into clubs (slug, name, short_name, category, tagline, description, verified, status)
values
  ('acm-student-chapter', 'ACM Student Chapter', 'ACM', 'PROFESSIONAL', 'Computing fundamentals, algorithms and the ACM chapter programme.', 'Computing fundamentals, algorithms and the ACM chapter programme. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('vit-ap-ieee-student-branch', 'VIT-AP IEEE Student Branch', 'IEEE', 'PROFESSIONAL', 'Technical talks, paper writing support and chapter activities.', 'Technical talks, paper writing support and chapter activities. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('computer-society-of-india', 'Computer Society of India', 'CSI', 'PROFESSIONAL', 'The CSI student chapter: workshops, seminars and industry sessions.', 'The CSI student chapter: workshops, seminars and industry sessions. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('machine-learning-club', 'Machine Learning Club', 'MLC', 'TECHNICAL', 'Applied machine learning projects and paper reading.', 'Applied machine learning projects and paper reading. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('innovators-quest-club', 'Innovators Quest Club', 'IQC', 'TECHNICAL', 'Build-first innovation projects and prototyping.', 'Build-first innovation projects and prototyping. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('open-source-community-vit-ap', 'Open Source Community: VIT-AP', 'OSC', 'TECHNICAL', 'Open source contribution, mentoring and community sprints.', 'Open source contribution, mentoring and community sprints. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('wios-women-in-open-source', 'WiOS — Women in Open Source', 'WiOS', 'TECHNICAL', 'Women contributing to and leading in open source.', 'Women contributing to and leading in open source. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('null-chapter', 'Null Chapter', 'null', 'TECHNICAL', 'The student null chapter: security research and hands-on sessions.', 'The student null chapter: security research and hands-on sessions. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('geeksforgeeks-vit-ap-student-chapter', 'GeeksforGeeks VIT-AP Student Chapter', 'GFG', 'TECHNICAL', 'Competitive programming, DSA practice and contests.', 'Competitive programming, DSA practice and contests. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('nextgen-cloud-club', 'NextGen Cloud Club', 'NGC', 'TECHNICAL', 'Cloud platforms, certification tracks and deployment workshops.', 'Cloud platforms, certification tracks and deployment workshops. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('seds-aurora', 'SEDS Aurora', 'SEDS', 'TECHNICAL', 'Students for the Exploration and Development of Space.', 'Students for the Exploration and Development of Space. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('photon-club', 'Photon Club', 'Photon', 'TECHNICAL', 'Photonics, optics and applied physics projects.', 'Photonics, optics and applied physics projects. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('be-a-nerd', 'Be A Nerd', 'BAN', 'TECHNICAL', 'A community for the deeply curious across every discipline.', 'A community for the deeply curious across every discipline. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('uddeshya-club', 'Uddeshya Club', 'Uddeshya', 'TECHNICAL', 'Purpose-driven technical projects and student initiatives.', 'Purpose-driven technical projects and student initiatives. A registered student club at VIT-AP, listed under Technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('western-music-club', 'Western Music Club', 'WMC', 'CULTURAL', 'Bands, jam sessions and western music performance.', 'Bands, jam sessions and western music performance. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('indian-classical-music-club', 'Indian Classical Music Club', 'ICMC', 'CULTURAL', 'Carnatic and Hindustani classical music practice and recitals.', 'Carnatic and Hindustani classical music practice and recitals. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('beat-the-heat-dance-club', 'Beat The Heat Dance Club', 'BTH', 'CULTURAL', 'Classical, western and street dance crews.', 'Classical, western and street dance crews. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('photography-club-vit-ap', 'Photography Club VIT-AP', 'PC', 'CREATIVE', 'Campus photowalks, editing sessions and print shows.', 'Campus photowalks, editing sessions and print shows. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('book-buzz-club', 'Book Buzz Club', 'BBC', 'CULTURAL', 'Reading circles, book discussions and author sessions.', 'Reading circles, book discussions and author sessions. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('ela-club', 'ELA Club', 'ELA', 'CULTURAL', 'English literary arts: writing, debate and expression.', 'English literary arts: writing, debate and expression. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('anchoring-club', 'Anchoring Club', 'AC', 'CULTURAL', 'Stage anchoring, hosting and public speaking practice.', 'Stage anchoring, hosting and public speaking practice. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('otaku-haven-club', 'Otaku Haven Club', 'OHC', 'CREATIVE', 'Anime, manga and pop-culture screenings and events.', 'Anime, manga and pop-culture screenings and events. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('knit', 'Knit', 'Knit', 'CREATIVE', 'Craft, knitting and hands-on making.', 'Craft, knitting and hands-on making. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('diy-club', 'DIY Club', 'DIY', 'CREATIVE', 'Do-it-yourself builds, repairs and creative projects.', 'Do-it-yourself builds, repairs and creative projects. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('spic-macay-heritage-club', 'SPIC MACAY Heritage Club', 'SPIC MACAY', 'CULTURAL', 'Indian classical arts and heritage appreciation.', 'Indian classical arts and heritage appreciation. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('kalki-personality-development-club', 'Kalki Personality Development Club', 'Kalki', 'SOCIAL', 'Personality development, soft skills and confidence building.', 'Personality development, soft skills and confidence building. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('think-and-thrive', 'Think and Thrive', 'T&T', 'SOCIAL', 'Critical thinking, wellbeing and personal growth sessions.', 'Critical thinking, wellbeing and personal growth sessions. A registered student club at VIT-AP, listed under Non-technical on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('chaitra-telugu-association', 'Chaitra Telugu Association', 'Chaitra', 'REGIONAL', 'Telugu language, literature and cultural celebration.', 'Telugu language, literature and cultural celebration. A registered student club at VIT-AP, listed under Regional Club & Chapters on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('semmozhi-tamil-mandram', 'Semmozhi Tamil Mandram', 'Semmozhi', 'REGIONAL', 'Tamil language and cultural programmes.', 'Tamil language and cultural programmes. A registered student club at VIT-AP, listed under Regional Club & Chapters on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('malayalam-association', 'Malayalam Association', 'MA', 'REGIONAL', 'Malayali culture, Onam celebrations and community.', 'Malayali culture, Onam celebrations and community. A registered student club at VIT-AP, listed under Regional Club & Chapters on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('namma-karunadu-kannada-association', 'Namma Karunadu Kannada Association', 'NKKA', 'REGIONAL', 'Kannada language and Karnataka cultural events.', 'Kannada language and Karnataka cultural events. A registered student club at VIT-AP, listed under Regional Club & Chapters on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('bengali-association-bongojo', 'Bengali Association: Bongojo', 'Bongojo', 'REGIONAL', 'Bengali culture, Durga Puja and community events.', 'Bengali culture, Durga Puja and community events. A registered student club at VIT-AP, listed under Regional Club & Chapters on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('haryana-association', 'Haryana Association', 'HA', 'REGIONAL', 'A home away from home for students from Haryana.', 'A home away from home for students from Haryana. A registered student club at VIT-AP, listed under Regional Club & Chapters on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('iete-students-forum', 'IETE Students Forum', 'ISF', 'PROFESSIONAL', 'The Institution of Electronics and Telecommunication Engineers student forum.', 'The Institution of Electronics and Telecommunication Engineers student forum. A registered student club at VIT-AP, listed under Professional Club on the university''s clubs and chapters page.', true, 'PUBLISHED'),
  ('rotaract-club', 'Rotaract Club', 'Rotaract', 'SOCIAL', 'Community service, outreach drives and social projects.', 'Community service, outreach drives and social projects. A registered student club at VIT-AP, listed under Social Outreach Club on the university''s clubs and chapters page.', true, 'PUBLISHED')
on conflict (slug) do update set
  name        = excluded.name,
  short_name  = excluded.short_name,
  category    = excluded.category,
  tagline     = excluded.tagline,
  description = excluded.description,
  verified    = excluded.verified;


insert into resources (slug, title, description, category, url, external, file_type, status)
values
  ('v-top-student-portal', 'V-TOP student portal', 'Attendance, marks, course registration, timetable and academic records.', 'PORTALS', 'https://vtop.vitap.ac.in/', true, null, 'PUBLISHED'),
  ('vit-ap-university-website', 'VIT-AP University website', 'The official university site.', 'PORTALS', 'https://vitap.ac.in/', true, null, 'PUBLISHED'),
  ('academic-calendar', 'Academic calendar', 'Official semester calendars for every programme and batch, including separate freshers calendars.', 'ACADEMIC_CALENDAR', 'https://vitap.ac.in/academiccalender', true, null, 'PUBLISHED'),
  ('fully-flexible-credit-system-ffcs', 'Fully Flexible Credit System (FFCS)', 'How course registration and the flexible credit system work at VIT.', 'ACADEMIC_CALENDAR', 'https://vitap.ac.in/ffcs', true, null, 'PUBLISHED'),
  ('fees-and-scholarships', 'Fees and scholarships', 'Fee structure, payment schedule and the scholarship schemes.', 'SCHOLARSHIP', 'https://vitap.ac.in/fees-and-scholarships', true, null, 'PUBLISHED'),
  ('hostels', 'Hostels', 'Hostel blocks, wardens, amenities, fee structure and the code of conduct.', 'HOSTEL', 'https://vitap.ac.in/hostels', true, null, 'PUBLISHED'),
  ('transport', 'Transport', 'University bus routes and the transport schedule.', 'IMPORTANT_LINKS', 'https://vitap.ac.in/transport', true, null, 'PUBLISHED'),
  ('library', 'Library', 'Library services, digital resources and access.', 'LIBRARY', 'https://vitap.ac.in/newlibrary', true, null, 'PUBLISHED'),
  ('healthcare', 'Healthcare', 'The campus health centre and medical support.', 'STUDENT_SERVICES', 'https://vitap.ac.in/healthcare', true, null, 'PUBLISHED'),
  ('career-development-centre', 'Career Development Centre', 'Placement preparation, training and the CDC office.', 'PLACEMENT', 'https://vitap.ac.in/cdc-overview', true, null, 'PUBLISHED'),
  ('placement-statistics', 'Placement statistics', 'Published placement outcomes and recruiter data.', 'PLACEMENT', 'https://vitap.ac.in/cdc-statistics', true, null, 'PUBLISHED'),
  ('dream-and-super-dream-offers', 'Dream and Super Dream offers', 'How the Dream and Super Dream placement categories work.', 'PLACEMENT', 'https://vitap.ac.in/cdc-superdream', true, null, 'PUBLISHED'),
  ('internships', 'Internships', 'Internship programmes and support.', 'PLACEMENT', 'https://vitap.ac.in/internships', true, null, 'PUBLISHED'),
  ('clubs-and-chapters', 'Clubs and chapters', 'The official directory of registered clubs and chapters.', 'IMPORTANT_LINKS', 'https://vitap.ac.in/clubs-and-chapters', true, null, 'PUBLISHED'),
  ('forms', 'Forms', 'Official university forms and applications.', 'FORMS', 'https://vitap.ac.in/forms', true, null, 'PUBLISHED'),
  ('directory', 'Directory', 'University contact directory.', 'IMPORTANT_LINKS', 'https://vitap.ac.in/directory', true, null, 'PUBLISHED'),
  ('policies', 'Policies', 'University policies and regulations.', 'IMPORTANT_LINKS', 'https://vitap.ac.in/policies', true, null, 'PUBLISHED'),
  ('academic-bank-of-credit-abc', 'Academic Bank of Credit (ABC)', 'The national Academic Bank of Credit, where your credits are deposited.', 'ACADEMIC_CALENDAR', 'https://www.abc.gov.in/', true, null, 'PUBLISHED'),
  ('equal-opportunity-cell', 'Equal Opportunity Cell', 'Support and redressal for equal opportunity matters.', 'STUDENT_SERVICES', 'https://vitap.ac.in/equal-opportunity-cell', true, null, 'PUBLISHED'),
  ('facilities-for-differently-abled-students', 'Facilities for differently-abled students', 'Accessibility provisions and support on campus.', 'STUDENT_SERVICES', 'https://vitap.ac.in/facilities-for-differently-abled', true, null, 'PUBLISHED'),
  ('e-samadhan-grievance-portal', 'e-Samadhan grievance portal', 'Raise and track a grievance with the university.', 'STUDENT_SERVICES', 'https://vitap.ac.in/e-samadhan', true, null, 'PUBLISHED'),
  ('gallery', 'Gallery', 'Photographs from campus events and celebrations.', 'IMPORTANT_LINKS', 'https://vitap.ac.in/gallery', true, null, 'PUBLISHED'),
  ('emergency-information', 'Emergency information', 'Emergency contacts and procedures published by the university.', 'EMERGENCY', 'https://vitap.ac.in/emergency-info', true, null, 'PUBLISHED')
on conflict (slug) do update set
  title       = excluded.title,
  description = excluded.description,
  category    = excluded.category,
  url         = excluded.url,
  file_type   = excluded.file_type;
